/**
 * Cloudflare R2 object storage, via its S3-compatible API.
 *
 * Hand-rolled SigV4 signing instead of @aws-sdk/client-s3 for the same
 * reason src/lib/payments/razorpay.ts hand-rolls its gateway calls: the one
 * operation this store needs (PUT an object) is ~60 lines, while the SDK is
 * a multi-megabyte dependency tree that would outweigh the rest of the
 * server code combined. If this ever grows past PUT/DELETE, switch to the
 * SDK rather than growing a signing library here.
 *
 * Env-gated: nothing here runs unless all five R2_* variables are set, so
 * the app keeps working (data-URL uploads into Postgres, as before) until
 * the owner creates the R2 bucket and pastes the keys. See .env.example.
 */

import { createHash, createHmac } from "node:crypto";

export function r2Config() {
  return {
    accountId: (process.env.R2_ACCOUNT_ID || "").trim(),
    accessKeyId: (process.env.R2_ACCESS_KEY_ID || "").trim(),
    secretAccessKey: (process.env.R2_SECRET_ACCESS_KEY || "").trim(),
    bucket: (process.env.R2_BUCKET || "").trim(),
    // Public base the bucket is served from — either the r2.dev development
    // URL or (better) a custom domain proxied through Cloudflare's CDN.
    publicBaseUrl: (process.env.R2_PUBLIC_BASE_URL || "").trim().replace(/\/+$/, ""),
  };
}

/** Whether object storage is fully configured on this deploy. */
export function r2Configured(): boolean {
  const c = r2Config();
  return Boolean(c.accountId && c.accessKeyId && c.secretAccessKey && c.bucket && c.publicBaseUrl);
}

const sha256Hex = (data: Buffer | string) => createHash("sha256").update(data).digest("hex");
const hmac = (key: Buffer | string, data: string) => createHmac("sha256", key).update(data).digest();

/**
 * PUT an object and return its public URL.
 *
 * AWS Signature Version 4, region "auto" (what R2 expects), service "s3".
 * The payload hash is signed, so a corrupted body is rejected by the server
 * rather than stored.
 */
export async function putR2Object(args: {
  key: string;
  body: Buffer;
  contentType: string;
  cacheControl?: string;
}): Promise<{ url: string }> {
  const c = r2Config();
  if (!r2Configured()) throw new Error("R2 storage is not configured");

  const host = `${c.accountId}.r2.cloudflarestorage.com`;
  // Every character except the unreserved set must be percent-encoded in the
  // canonical URI. Keys are generated by us (see the upload route), but the
  // encoding is still done properly so a future key scheme can't break signing.
  const canonicalUri = `/${c.bucket}/${args.key
    .split("/")
    .map((s) => encodeURIComponent(s))
    .join("/")}`;

  const now = new Date();
  const amzDate = now.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, ""); // YYYYMMDDTHHMMSSZ
  const dateStamp = amzDate.slice(0, 8);
  const payloadHash = sha256Hex(args.body);

  const headers: Record<string, string> = {
    host,
    "content-type": args.contentType,
    "x-amz-content-sha256": payloadHash,
    "x-amz-date": amzDate,
  };
  if (args.cacheControl) headers["cache-control"] = args.cacheControl;

  const signedHeaderNames = Object.keys(headers).sort();
  const canonicalHeaders = signedHeaderNames.map((h) => `${h}:${headers[h].trim()}\n`).join("");
  const signedHeaders = signedHeaderNames.join(";");

  const canonicalRequest = ["PUT", canonicalUri, "", canonicalHeaders, signedHeaders, payloadHash].join("\n");
  const scope = `${dateStamp}/auto/s3/aws4_request`;
  const stringToSign = ["AWS4-HMAC-SHA256", amzDate, scope, sha256Hex(canonicalRequest)].join("\n");

  const kDate = hmac(`AWS4${c.secretAccessKey}`, dateStamp);
  const kRegion = hmac(kDate, "auto");
  const kService = hmac(kRegion, "s3");
  const kSigning = hmac(kService, "aws4_request");
  const signature = createHmac("sha256", kSigning).update(stringToSign).digest("hex");

  const authorization =
    `AWS4-HMAC-SHA256 Credential=${c.accessKeyId}/${scope}, ` +
    `SignedHeaders=${signedHeaders}, Signature=${signature}`;

  const res = await fetch(`https://${host}${canonicalUri}`, {
    method: "PUT",
    headers: { ...headers, authorization },
    body: new Uint8Array(args.body),
    // Same 15s discipline as the payment gateway client: a hung storage call
    // must fail the upload request, not hold the admin's browser forever.
    signal: AbortSignal.timeout(15000),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`R2 PUT failed: ${res.status} ${text.slice(0, 300)}`);
  }

  return { url: `${c.publicBaseUrl}/${args.key}` };
}
